### ISSUE TITLE
304 status on config and commands

### ISSUE THREAD

**Issue by aamccaslin** [beer-garden/brew-view#33]
Trying to access the server and going to **#!/commands** will give a **304** status and the loading wheel will be loading infinitely. Accessing the server at **api/v1/commands/** will give a **200** status and load all of the response headers that didn't load before such as "Content-Type" and "Content-Length"

**Comment by hazmat345** [comment]
Think this is OBE, can't replicate anymore. Going to `#!/commands` seems to work, as does doing a hard refresh.

Going to `#!/commands/` results in a 'command not found page'. It looks like angular is matching the commands/:id route with no id, so that makes sense. Going to close this as OBE.
