### ISSUE TITLE
Pour it again Multiple versions of a plugin

### ISSUE THREAD

**Issue by loganasherjones** [beer-garden/brew-view#45]
If you have multiple versions of the same plugin and those versions have different instance_names. When you hit "Pour it again" it does not correctly match the system version.

**Comment by hazmat345** [comment]
I can't replicate this anymore ... I'm wondering if beer-garden/beer-garden#98 fixed this as well.

**Comment by hazmat345** [comment]
I still can't replicate this - going to say this was OBE and close.
